import {SCALES, LEVELS, generate, midi, stavePosition} from './core.mjs';
import {CLEF_PATHS} from './clefs.mjs';
(()=>{'use strict';
const $=id=>document.getElementById(id),parts=[['concert','Concert / flute','Treble clef'],['clarinet','B♭ / clarinet','Below the break'],['trumpet','B♭ / trumpet','Treble clef'],['alto','E♭ / alto sax','Treble clef'],['bass','Bass clef / low brass','Concert pitch'],['mallets','Mallets','Treble clef · octave below flute']];
let bars=[],count=1,heard=false,ctx=null,playbackGain=null,voices=[],timers=[],clickTimer=null,metroTimer=null,metroOn=false,trackerOn=true,tempo=68;
function schedule(fn,ms){const id=setTimeout(fn,ms);timers.push(id);return id}
function make(){clearTimeout(clickTimer);clickTimer=null;stop();const level=+$('level').value;bars=generate(level,+$('measures').value);heard=false;$('proceed').textContent='Hear this exercise';$('replay').hidden=true;$('exercise-number').textContent=`EXERCISE ${count}`;$('score-title').textContent=`Level ${level} · ${bars.length} measures`;$('status').textContent='Ready to read';render()}
function tag(t,a,inner=''){return `<${t} ${Object.entries(a).map(([k,v])=>`${k}="${v}"`).join(' ')}>${inner}</${t}>`}
function accidental(kind,x,y,measure){const path=kind==='flat'?`M ${x-19} ${y-19} V ${y+7} C ${x-13} ${y+7},${x-9} ${y+1},${x-11} ${y-4} C ${x-12} ${y-9},${x-17} ${y-7},${x-19} ${y-4}`:`M ${x-20} ${y-13} V ${y+12} M ${x-13} ${y-15} V ${y+10} M ${x-23} ${y-4} L ${x-10} ${y-7} M ${x-23} ${y+5} L ${x-10} ${y+2}`;return `<path ${measure===undefined?'class="key-flat"':`data-accidental="${kind}" data-measure="${measure}"`} d="${path}" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/>`}
const TIME_FOUR_PATH='M715 506V1300L205 506ZM1155 0H475V106H715V399H63V508L717 1520H915V506H1200V399H915V106H1155Z';
function levelHasCourtesy(){return +$('level').value<7}
function renderPart(key,label,sub){const clef=key==='bass'?'bass':'treble',sw=bars.length===8?2300:1120,sh=170,barWidth=(sw-220)/bars.length;let svg='';const top=58,bottom=98,start=195;for(let i=0;i<5;i++)svg+=tag('line',{x1:16,y1:top+i*10,x2:sw-25,y2:top+i*10,'stroke-width':1.2});svg+=tag('path',{d:CLEF_PATHS[clef],transform:clef==='bass'?`translate(45 ${top+10}) scale(.055 -.055)`:`translate(45 ${top+30}) scale(.045 -.045)`,class:'clef',fill:'currentColor'});if(key==='alto'){svg+=tag('text',{x:97,y:top+19,'font-size':30},'♯')}else if(key!=='trumpet'&&key!=='clarinet'){svg+=accidental('flat',112,clef==='bass'?top+30:top+20)+accidental('flat',135,clef==='bass'?top+15:top+5)}for(const offset of [0,20])svg+=tag('path',{d:TIME_FOUR_PATH,transform:`translate(149 ${top+offset+20}) scale(.01407 -.01316) translate(-63 0)`,class:'time-signature',fill:'currentColor'});
for(let b=0;b<bars.length;b++){const bar=bars[b],x0=start+b*barWidth;let beat=0,notes=[],prevX=x0-10;for(let i=0;i<bar.length;i++){const ev=bar[i],n=SCALES[key][ev.index],courtesy=levelHasCourtesy() ? (n.includes('b')?'flat':n.includes('#')?'sharp':'') : '',rawX=x0+12+(beat+ev.duration/2)/4*(barWidth-24)+(ev.pair==='start'?-12:ev.pair==='end'?12:0),x=Math.max(rawX,x0+30,prevX+(courtesy?34:21)),pos=stavePosition(n,clef),y=bottom-pos*5,idx=bars.slice(0,b).reduce((n,r)=>n+r.length,0)+i;notes.push({x,y,ev,idx});prevX=x;let group=`data-event="${idx}"`;
if(ev.kind==='rest')svg+=`<text ${group} x="${x-7}" y="${top+29}" font-size="27" class="rest">𝄽</text>`;else{for(let p=-2;p>=pos;p-=2)svg+=tag('line',{x1:x-13,y1:bottom-p*5,x2:x+14,y2:bottom-p*5,'stroke-width':1.5});for(let p=10;p<=pos;p+=2)svg+=tag('line',{x1:x-13,y1:bottom-p*5,x2:x+14,y2:bottom-p*5,'stroke-width':1.5});if(courtesy)svg+=accidental(courtesy,x,y,b);let open=ev.duration>=2;svg+=`<ellipse ${group} cx="${x}" cy="${y}" rx="7.5" ry="5" transform="rotate(-20 ${x} ${y})" class="${open?'open':'note'}" stroke-width="1.5"/>`;if(ev.duration!==4){const partner=ev.kind==='eighth'?bar[i+(ev.pair==='start'?1:-1)]:null,partnerPos=partner?stavePosition(SCALES[key][partner.index],clef):0,up=ev.kind==='eighth'?(pos<=4&&partnerPos<=4):pos<=4,sx=x+(up?7:-7),sy=y+(up?-30:30);svg+=tag('line',{x1:sx,y1:y,x2:sx,y2:sy,'stroke-width':1.8});}if(ev.accent)svg+=tag('text',{x:x-6,y:y-14,'font-size':18},'>');if(ev.staccato)svg+=`<circle cx="${x}" cy="${y+13}" r="2" fill="currentColor"/>`}
beat+=ev.duration}for(let i=0;i<notes.length-1;i++){if(notes[i].ev.pair==='start'){const a=notes[i],z=notes[i+1],up=stavePosition(SCALES[key][a.ev.index],clef)<=4&&stavePosition(SCALES[key][z.ev.index],clef)<=4;let ay=a.y+(up?-30:30),zy=z.y+(up?-30:30);svg+=tag('line',{x1:a.x+(up?7:-7),y1:ay,x2:z.x+(up?7:-7),y2:zy,'stroke-width':5})}}svg+=b===bars.length-1?tag('line',{x1:x0+barWidth-7,y1:top,x2:x0+barWidth-7,y2:top+40,class:'bar','stroke-width':1.5})+tag('line',{x1:x0+barWidth,y1:top,x2:x0+barWidth,y2:top+40,class:'end-bar','stroke-width':4}):tag('line',{x1:x0+barWidth,y1:top,x2:x0+barWidth,y2:top+40,class:'bar','stroke-width':1.5})}if(LEVELS[+$('level').value].expression)svg+=tag('text',{x:195,y:top+75,'font-size':18,class:'dynamic'},'mf')
return `<section class="part"><div class="part-label">${label}<small>${sub}</small></div><div class="staff-scroll"><svg class="staff" viewBox="0 0 ${sw} ${sh}" role="img" aria-label="${label}, ${bars.length} measures">${svg}</svg></div></section>`}
function render(){let chosen=$('mode').value==='class'?parts:parts.filter(p=>p[0]===$('instrument').value);$('scores').innerHTML=chosen.map(p=>renderPart(...p)).join('');document.body.classList.toggle('eight',bars.length===8)}function highlight(i){document.querySelectorAll('.active-note,.active-rest').forEach(e=>e.classList.remove('active-note','active-rest'));if(i<0)return;document.querySelectorAll(`[data-event="${i}"]`).forEach(e=>e.classList.add(e.tagName.toLowerCase()==='text'?'active-rest':'active-note'))}
function stop(){timers.forEach(clearTimeout);timers=[];$('metro').disabled=false;voices.forEach(o=>{try{o.stop()}catch(_){}});voices=[];highlight(-1);$('play-along').textContent='Play along';$('play-along').setAttribute('aria-pressed','false')}function audio(){const C=window.AudioContext||window.webkitAudioContext;if(!C){$('status').textContent='Audio unavailable';return null}if(!ctx){ctx=new C();playbackGain=ctx.createGain();playbackGain.gain.value=+$('playback-volume').value/100;playbackGain.connect(ctx.destination)}ctx.resume();return ctx}
// Soft, short-decay piano-like partials with no sharp square-wave edge.
function piano(note,when,length,volume=.085){const c=audio();if(!c)return;const fundamental=440*Math.pow(2,(midi(note)-69)/12);[1,2,3].forEach((harmonic,i)=>{let o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=fundamental*harmonic;let peak=volume*[1,.24,.08][i];g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(peak,when+.018);g.gain.exponentialRampToValueAtTime(.0001,when+Math.min(length*.95,1.7));o.connect(g).connect(playbackGain);o.start(when);o.stop(when+Math.min(length,1.8));voices.push(o);o.onended=()=>{voices=voices.filter(node=>node!==o)}})}
function reference(){stop();const c=audio();if(!c)return;let beat=60/tempo,time=0;bars.flat().forEach(ev=>{if(ev.kind!=='rest')piano(SCALES.concert[ev.index],c.currentTime+.12+time*beat,ev.duration*beat*.95);time+=ev.duration});$('status').textContent='Playing reference…';schedule(()=>{$('status').textContent='Practice again or proceed'},time*beat*1000+200)}
function along(){stop();stopMetro();const c=audio();if(!c)return;const beat=60/tempo,events=bars.flat();$('metro').disabled=true;$('status').textContent='Count in: 4';for(let i=0;i<4;i++)schedule(()=>{$('status').textContent=`Count in: ${4-i}`;click(true)},i*beat*1000);for(let i=0;i<bars.length*4;i++)schedule(()=>click(false),(4+i)*beat*1000);let t=4;events.forEach((ev,i)=>{const current=t;schedule(()=>{if(trackerOn)highlight(i);$('status').textContent=`Measure ${Math.floor((current-4)/4)+1} of ${bars.length}`},current*beat*1000);t+=ev.duration});schedule(()=>{$('status').textContent='Finished';highlight(-1);$('play-along').textContent='Play along';$('play-along').setAttribute('aria-pressed','false');$('metro').disabled=false},t*beat*1000);$('play-along').textContent='Stop play along';$('play-along').setAttribute('aria-pressed','true')}function click(countIn=false){let c=audio();if(!c)return;let o=c.createOscillator(),g=c.createGain(),t=c.currentTime;o.type='sine';o.frequency.value=countIn?730:520;g.gain.setValueAtTime(countIn?.045:.035,t);g.gain.exponentialRampToValueAtTime(.0001,t+(countIn?.11:.08));o.connect(g).connect(c.destination);o.start(t);o.stop(t+.12);voices.push(o);o.onended=()=>{voices=voices.filter(node=>node!==o)}}
$('proceed').addEventListener('click',()=>{if(clickTimer)return;clickTimer=setTimeout(()=>{clickTimer=null;if(heard){count++;make()}else{heard=true;$('proceed').textContent='Proceed to next';$('replay').hidden=false;reference()}},280)});$('proceed').addEventListener('dblclick',()=>{clearTimeout(clickTimer);clickTimer=null;count++;make()});$('replay').onclick=reference;$('new-exercise').onclick=()=>{clearTimeout(clickTimer);clickTimer=null;count++;make()};
$('theme').onclick=()=>{let dark=document.body.classList.toggle('dark');$('theme').textContent=dark?'☀ Light mode':'☾ Dark mode';$('theme').setAttribute('aria-pressed',String(dark));localStorage.setItem('sight-theme',dark?'dark':'light')};if(localStorage.getItem('sight-theme')==='dark')$('theme').click();
$('mode').onchange=()=>{let single=$('mode').value==='single';$('instrument-wrap').hidden=!single;$('tempo-wrap').hidden=!single;$('new-exercise').hidden=single;$('play-along').hidden=!single;$('tracker').hidden=!single;stop();stopMetro();render()};$('instrument').onchange=render;$('level').onchange=make;$('measures').onchange=make;
$('playback-volume').oninput=()=>{const percentage=+$('playback-volume').value;$('playback-volume-value').value=`${percentage}%`;if(playbackGain)playbackGain.gain.setTargetAtTime(percentage/100,ctx.currentTime,.01)};$('tempo-slider').oninput=()=>{tempo=+$('tempo-slider').value;$('tempo-value').value=`${tempo} BPM`;if(metroOn){stopMetro();startMetro()}};$('play-along').onclick=()=>{if($('play-along').textContent==='Stop play along'){stop();$('status').textContent='Stopped'}else along()};$('tracker').onclick=()=>{trackerOn=!trackerOn;$('tracker').textContent=`Tracker: ${trackerOn?'on':'off'}`;$('tracker').setAttribute('aria-pressed',String(trackerOn));if(!trackerOn)highlight(-1)};
function stopMetro(){clearInterval(metroTimer);metroTimer=null;metroOn=false;$('metro').textContent='Metronome: off';$('metro').setAttribute('aria-pressed','false')}function startMetro(){metroOn=true;$('metro').textContent='Metronome: on';$('metro').setAttribute('aria-pressed','true');click();metroTimer=setInterval(click,60000/tempo)}$('metro').onclick=()=>metroOn?stopMetro():startMetro();const params=new URLSearchParams(location.search);if(params.get('view')==='single'){$('mode').value='single';for(const id of ['instrument','level','measures']){const value=params.get(id);if(value&&Array.from($(id).options).some(option=>option.value===value))$(id).value=value}$('mode').onchange()}make();})();
